### PR TITLE
Added Dockerfile

### PR DESCRIPTION
**Pull request by Mikerah**
I added a dockerfile in order to enable others to run this code as it contains dependencies that are no longer available in modern Ubuntu versions.

### CODE REVIEW

**Comment by wangxiao1254** [comment]
Thanks!!

**Comment by Saisai-Xia** [comment]
> 



> I added a dockerfile in order to enable others to run this code as it contains dependencies that are no longer available in modern Ubuntu versions.

Hello, I am using the dockerfile to build the project environment, but when I execute the command to compile the c code, it always prompts me that there is no input file, and the following is the command that reports the error
./scripts/compileBinary.sh ./source_programs/set_intersection.c
May I ask if you have encountered such a problem and how to solve it?

**Comment by Mikerah** [comment]
@Saisai-Xia Some of the c files actually don't compile/work easily. If I recall correctly, the set intersection file was one of them. If you use a different c file, the Dockerfile works.

**Comment by Saisai-Xia** [comment]
> @Saisai-Xia Some of the c files actually don't compile/work easily. If I recall correctly, the set intersection file was one of them. If you use a different c file, the Dockerfile works.

I tried most of the files in the "source_programs" provided by the author, and they all had the same error, but the author did complete the compilation in the performance analysis part of the paper. The following is the error message prompted under the ubuntu terminal
: No such file or directory: source_programs/hamming.c
mipsel-linux-gnu-gcc: fatal error: no input files
compilation terminated.

But if I use the mipsel-linux-gnu-gcc command directly, the compilation can be completed.
Looking forward to your reply

**Pull request merged**
